name: medimart
description: "A new Flutter project for MediMart."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking and API handling
  http: ^1.2.2
  
  # Firebase core and related packages
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  


  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/ # Ensure this directory exists and contains assets
